CREATE VIEW VIEW_CROP_COMB
AS
SELECT CROP,NAME,START_OF_SEASON,END_OF_SEASON,IMAGE_PATH
	FROM GISTEACH.CROPS B 
	LEFT JOIN S1783947.FF_CROP_IMAGES D ON B.CROP = D.CROP_ID
UNION
SELECT CROP,NAME,START_OF_SEASON,END_OF_SEASON,IMAGE_PATH
	FROM FF_CROPS_NEW;