CREATE TABLE FF_FIELDS_NEW
(FIELD_ID NUMBER(2) NOT NULL,
LOWX NUMBER(2) CHECK (LOWX BETWEEN 0 AND 50),
LOWY NUMBER(2) CHECK (LOWY BETWEEN 0 AND 50),
HIX NUMBER(2) CHECK (HIX BETWEEN 1 AND 50),
HIY NUMBER(2) CHECK (HIY BETWEEN 1 AND 50),
AREA NUMBER(5,2) CHECK (AREA BETWEEN 0 AND 2500), 
OWNER VARCHAR(50),
CROP NUMBER(4),
AREA_ID NUMBER(2) NOT NULL,
PRIMARY KEY (FIELD_ID),
FOREIGN KEY (AREA_ID) REFERENCES FF_AREA(AREA_ID),
FOREIGN KEY (OWNER) REFERENCES FF_FARMERS(FARMER_NAME));
