CREATE TABLE FF_FINDS_NEW
(FIND_ID NUMBER(4) NOT NULL,
XCOORD NUMBER(2) CHECK (XCOORD BETWEEN 0 AND 50),
YCOORD NUMBER(2) CHECK (YCOORD BETWEEN 0 AND 50),
TYPE NUMBER(4),
DEPTH NUMBER(4,2) CHECK (DEPTH BETWEEN 0 AND 30), 
FIELD_NOTES VARCHAR(100),
AREA_ID NUMBER(2) NOT NULL,
IMAGE_PATH VARCHAR(1000),
PRIMARY KEY (FIND_ID),
FOREIGN KEY (AREA_ID) REFERENCES FF_AREA(AREA_ID));