CREATE TABLE FF_CROPS_NEW
(CROP NUMBER(4) NOT NULL,
NAME VARCHAR(30),
START_OF_SEASON DATE CHECK (START_OF_SEASON>'31-Dec-1986'),
END_OF_SEASON DATE CHECK (END_OF_SEASON>'31-Dec-1986'),
IMAGE_PATH VARCHAR(1000),
PRIMARY KEY (CROP));


