CREATE VIEW VIEW_FINDS_NEW
AS
SELECT
	A.FIND_ID AS "OBJECT_ID",
	A.XCOORD AS "X",
	A.YCOORD AS "Y",
	A.DEPTH AS "DEPTH",
	A.FIELD_NOTES AS "FIELD_NOTES",
	B.NAME AS "TYPE",
	B.PERIOD AS "PERIOD",
	B.USE AS "USE",
	A.AREA_ID AS "AREA_ID",
	B.COLOUR AS "COLOUR",
	A.IMAGE_PATH AS "FIND_IMAGE"
	FROM S1783947.FF_FINDS_NEW A
	LEFT JOIN S1783947.VIEW_CLASS_COMB B ON A.TYPE = B.TYPE
	ORDER BY A.FIND_ID;