CREATE VIEW VIEW_CLASS_COMB
AS
SELECT TYPE,NAME,PERIOD,USE,COLOUR
	FROM GISTEACH.CLASS B 
	LEFT JOIN S1783947.FF_FIND_COLOUR C ON B.TYPE = C.TYPE_ID
UNION
SELECT TYPE,NAME,PERIOD,USE,COLOUR FROM FF_CLASS_NEW;